#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 John Knipper
#
# The libraries and devices AROS itself ships, which a program may open
# without depending on a package: the .library files of Libs/ and Classes/,
# the .device files of Devs/, and the modules of the boot images, read from
# a nightly's boot ISO tree. Writes tools/aros/system-libraries.txt and
# src/pkg_syslibs.h, which Pkg compiles in.
#
#     sh tools/aros/gen-system-libraries.sh <boot ISO tree>
set -eu
tree=${1:?usage: gen-system-libraries.sh <boot ISO tree>}
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
txt="$here/system-libraries.txt"
hdr="$here/../../src/pkg_syslibs.h"
{
    ls "$tree/Libs" "$tree/Classes" 2>/dev/null | grep -E '\.library$' || true
    ls "$tree/Devs" 2>/dev/null | grep -E '\.device$' || true
    for f in "$tree"/boot/*.pkg.xz "$tree"/boot/*/*.pkg.xz; do
        [ -f "$f" ] || continue
        LC_ALL=C xz -dc "$f" | LC_ALL=C strings | LC_ALL=C grep -oE '^\$VER: [A-Za-z0-9_.-]+\.(library|device)' | sed 's/^\$VER: //'
    done
} | LC_ALL=C sort -fu > "$txt.new"
mv "$txt.new" "$txt"
{
    echo "/* Generated by tools/aros/gen-system-libraries.sh from $(basename "$tree"): the libraries"
    echo " * and devices AROS ships. Do not edit; run the script on a newer nightly. */"
    echo "static const char *const pkg_system_libs[] = {"
    sed 's/.*/    "&",/' "$txt"
    echo "    NULL"
    echo "};"
} > "$hdr"
echo "gen-system-libraries: $(wc -l < "$txt" | tr -d ' ') names"
