#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 John Knipper
#
# The certificate authorities as a C file, on stdout. AROS has no system
# store of authorities, so the AROS builds of Pkg carry the bundle of
# third_party/cacert inside the program; the C file is generated by the build
# and is never checked in. PKG_CAFILE names another bundle at run time.

set -eu
pem=${1:?usage: ca-bundle-c.sh <cacert.pem>}

echo "/* Generated by tools/ca-bundle-c.sh from $(basename "$pem"); do not edit. */"
echo "const unsigned char pkg_ca_pem[] ="
awk '{ gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); printf "\"%s\\n\"\n", $0 }' "$pem"
echo ";"
echo "const unsigned int pkg_ca_pem_len = sizeof pkg_ca_pem - 1;"
